services:
  - type: web
    name: lavalust-product-management
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: DB_DRIVER
        value: mysql
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_CHARSET
        value: utf8mb4
      - key: DB_PREFIX
        value: ""
      - key: DB_SSL_CA
        sync: false
      - key: ALLOW_ORIGIN
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: REFRESH_TOKEN_KEY
        sync: false
